options:
  pool:
    name: 'projects/spry-optics-373609/locations/europe-west2/workerPools/private-pool-build'
  pool:
    name: 'projects/spry-optics-373609/locations/europe-west2/workerPools/private-pool-build'
steps:
  # Étape pour tirer l'image de cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker pull eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:latest || exit 0

  # Étape pour construire l'image en utilisant le cache existant
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:$COMMIT_SHA',
      '-t', 'eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:latest',
      '--cache-from', 'eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:latest',
      '.'
    ]

  # Étape pour pousser l'image avec le tag du commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:$COMMIT_SHA']

  # Étape pour taguer l'image en 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:$COMMIT_SHA', 'eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:latest']

  # Étape pour pousser l'image taguée 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:latest']

images:
  - 'eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:$COMMIT_SHA'
  - 'eu.gcr.io/spry-optics-373609/github.com/maximedotair/hero-name:latest'
